import csv
import torch

# Load 80 cell lines from heterodata to ensure 100% coverage
data = torch.load("data/processed/heterodata.pt", map_location="cpu", weights_only=False)
expected_cell_lines = sorted(list(data.cell_line_map.keys()))

metadata = [
    # CNS / Brain (6 lines)
    {
        "cell_line_name": "T98G",
        "depmap_id": "ACH-000231",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,brain,cns,brain cancer,brain tumor,neuroepithelioma",
    },
    {
        "cell_line_name": "U251",
        "depmap_id": "ACH-000244",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,brain,cns,brain cancer,brain tumor,malignant glioma",
    },
    {
        "cell_line_name": "SF-268",
        "depmap_id": "ACH-000412",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma / Astrocytoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,brain,cns,brain cancer,brain tumor",
    },
    {
        "cell_line_name": "SF-295",
        "depmap_id": "ACH-000146",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,brain,cns,brain cancer,brain tumor",
    },
    {
        "cell_line_name": "SF-539",
        "depmap_id": "ACH-000249",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma / Gliosarcoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,gliosarcoma,brain,cns,brain cancer,brain tumor",
    },
    {
        "cell_line_name": "SNB-75",
        "depmap_id": "ACH-000237",
        "tissue": "CNS / Brain",
        "cancer_type": "Glioblastoma",
        "lineage": "central_nervous_system",
        "keywords": "glioblastoma,gbm,glioma,astrocytoma,brain,cns,brain cancer,brain tumor",
    },

    # Lung / NSCLC (13 lines)
    {
        "cell_line_name": "A549",
        "depmap_id": "ACH-000681",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary,bronchial,non-small cell lung carcinoma",
    },
    {
        "cell_line_name": "A427",
        "depmap_id": "ACH-000788",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary,non-small cell lung carcinoma",
    },
    {
        "cell_line_name": "EKVX",
        "depmap_id": "ACH-000869",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary,non-small cell lung carcinoma",
    },
    {
        "cell_line_name": "HOP-62",
        "depmap_id": "ACH-000757",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary,non-small cell lung carcinoma",
    },
    {
        "cell_line_name": "HOP-92",
        "depmap_id": "ACH-000810",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary,non-small cell lung carcinoma",
    },
    {
        "cell_line_name": "NCI-H226",
        "depmap_id": "ACH-000508",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Squamous)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,squamous cell lung,squamous cell carcinoma,pulmonary,mesothelioma",
    },
    {
        "cell_line_name": "NCI-H322M",
        "depmap_id": "ACH-000350",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Bronchioloalveolar)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,pulmonary,bronchioloalveolar",
    },
    {
        "cell_line_name": "NCI-H522",
        "depmap_id": "ACH-000632",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary",
    },
    {
        "cell_line_name": "NCIH1650",
        "depmap_id": "ACH-000216",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (EGFR-mutant)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,egfr,pulmonary",
    },
    {
        "cell_line_name": "NCIH2122",
        "depmap_id": "ACH-000707",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,kras,pulmonary",
    },
    {
        "cell_line_name": "NCIH23",
        "depmap_id": "ACH-000684",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Adenocarcinoma)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,adenocarcinoma,lung adenocarcinoma,pulmonary",
    },
    {
        "cell_line_name": "NCIH520",
        "depmap_id": "ACH-000454",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Squamous)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,squamous cell lung,pulmonary",
    },
    {
        "cell_line_name": "SKMES1",
        "depmap_id": "ACH-000490",
        "tissue": "Lung",
        "cancer_type": "Non-Small Cell Lung Carcinoma (Squamous)",
        "lineage": "lung",
        "keywords": "lung,lung cancer,nsclc,squamous cell lung,pulmonary",
    },

    # Breast (8 lines)
    {
        "cell_line_name": "MCF7",
        "depmap_id": "ACH-000019",
        "tissue": "Breast",
        "cancer_type": "Breast Carcinoma (ER+ / Luminal)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,er+,luminal,breast neoplasm",
    },
    {
        "cell_line_name": "MDA-MB-231",
        "depmap_id": "ACH-000768",
        "tissue": "Breast",
        "cancer_type": "Triple-Negative Breast Carcinoma (TNBC)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,tnbc,triple negative breast cancer,basal-like",
    },
    {
        "cell_line_name": "MDA-MB-468",
        "depmap_id": "ACH-000849",
        "tissue": "Breast",
        "cancer_type": "Triple-Negative Breast Carcinoma (TNBC)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,tnbc,triple negative,egfr+",
    },
    {
        "cell_line_name": "MDAMB436",
        "depmap_id": "ACH-000624",
        "tissue": "Breast",
        "cancer_type": "Triple-Negative Breast Carcinoma (BRCA1-mutant)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,tnbc,brca1",
    },
    {
        "cell_line_name": "BT-549",
        "depmap_id": "ACH-000498",
        "tissue": "Breast",
        "cancer_type": "Triple-Negative Breast Carcinoma (Ductal)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,tnbc,ductal carcinoma",
    },
    {
        "cell_line_name": "HS 578T",
        "depmap_id": "ACH-000148",
        "tissue": "Breast",
        "cancer_type": "Breast Carcinoma (Ductal / TNBC)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,tnbc,ductal carcinoma",
    },
    {
        "cell_line_name": "T-47D",
        "depmap_id": "ACH-000929",
        "tissue": "Breast",
        "cancer_type": "Breast Carcinoma (ER+ / PR+)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary,er+,pr+,luminal",
    },
    {
        "cell_line_name": "OCUBM",
        "depmap_id": "ACH-000075",
        "tissue": "Breast",
        "cancer_type": "Breast Carcinoma (Bone metastatic)",
        "lineage": "breast",
        "keywords": "breast,breast cancer,breast carcinoma,mammary",
    },

    # Colon / Colorectal (10 lines)
    {
        "cell_line_name": "HCT116",
        "depmap_id": "ACH-000971",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel,rectal,intestinal,kras",
    },
    {
        "cell_line_name": "HT29",
        "depmap_id": "ACH-000561",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel,rectal,intestinal,braf",
    },
    {
        "cell_line_name": "COLO 205",
        "depmap_id": "ACH-000955",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel,rectal",
    },
    {
        "cell_line_name": "HCC-2998",
        "depmap_id": "ACH-000669",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "HCT-15",
        "depmap_id": "ACH-000972",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "KM12",
        "depmap_id": "ACH-000958",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "LOVO",
        "depmap_id": "ACH-000966",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "RKO",
        "depmap_id": "ACH-000045",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "SW-620",
        "depmap_id": "ACH-000650",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Colorectal Carcinoma (Lymph node metastatic)",
        "lineage": "bowel",
        "keywords": "colon,colorectal,colon cancer,colorectal carcinoma,colorectal cancer,bowel",
    },
    {
        "cell_line_name": "SW837",
        "depmap_id": "ACH-000762",
        "tissue": "Colon / Colorectal",
        "cancer_type": "Rectal Carcinoma",
        "lineage": "bowel",
        "keywords": "colon,colorectal,rectal,rectum,colorectal cancer,bowel",
    },

    # Ovary (11 lines)
    {
        "cell_line_name": "OVCAR-5",
        "depmap_id": "ACH-000223",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,ovarian carcinoma,epithelial ovarian cancer,peritoneal",
    },
    {
        "cell_line_name": "A2780",
        "depmap_id": "ACH-000673",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,ovarian carcinoma,epithelial ovarian cancer",
    },
    {
        "cell_line_name": "ES2",
        "depmap_id": "ACH-000938",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Clear Cell Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian clear cell,clear cell carcinoma,ovarian cancer",
    },
    {
        "cell_line_name": "IGROV1",
        "depmap_id": "ACH-000843",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,ovarian carcinoma",
    },
    {
        "cell_line_name": "OV90",
        "depmap_id": "ACH-000714",
        "tissue": "Ovary",
        "cancer_type": "High-Grade Serous Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,serous ovarian,high-grade serous",
    },
    {
        "cell_line_name": "OVCAR-4",
        "depmap_id": "ACH-000779",
        "tissue": "Ovary",
        "cancer_type": "High-Grade Serous Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,serous ovarian",
    },
    {
        "cell_line_name": "OVCAR-8",
        "depmap_id": "ACH-000806",
        "tissue": "Ovary",
        "cancer_type": "High-Grade Serous Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,serous ovarian",
    },
    {
        "cell_line_name": "OVCAR3",
        "depmap_id": "ACH-000805",
        "tissue": "Ovary",
        "cancer_type": "High-Grade Serous Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,serous ovarian",
    },
    {
        "cell_line_name": "PA1",
        "depmap_id": "ACH-000880",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Teratocarcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,teratocarcinoma,germ cell tumor",
    },
    {
        "cell_line_name": "SK-OV-3",
        "depmap_id": "ACH-000789",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Carcinoma",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,ovarian carcinoma,her2+",
    },
    {
        "cell_line_name": "UWB1289",
        "depmap_id": "ACH-000867",
        "tissue": "Ovary",
        "cancer_type": "Ovarian Carcinoma (BRCA1-null)",
        "lineage": "ovary",
        "keywords": "ovary,ovarian,ovarian cancer,brca1",
    },

    # Skin / Melanoma (11 lines)
    {
        "cell_line_name": "A375",
        "depmap_id": "ACH-000219",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma (BRAF V600E)",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma,braf,malignant melanoma",
    },
    {
        "cell_line_name": "A2058",
        "depmap_id": "ACH-000511",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma,braf",
    },
    {
        "cell_line_name": "HT144",
        "depmap_id": "ACH-000705",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },
    {
        "cell_line_name": "LOX IMVI",
        "depmap_id": "ACH-000868",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },
    {
        "cell_line_name": "M14",
        "depmap_id": "ACH-000452",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },
    {
        "cell_line_name": "RPMI7951",
        "depmap_id": "ACH-000305",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },
    {
        "cell_line_name": "SK-MEL-2",
        "depmap_id": "ACH-000883",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma (NRAS-mutant)",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma,nras",
    },
    {
        "cell_line_name": "SK-MEL-28",
        "depmap_id": "ACH-000445",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma (BRAF-mutant)",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma,braf",
    },
    {
        "cell_line_name": "SK-MEL-5",
        "depmap_id": "ACH-000448",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma (BRAF-mutant)",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma,braf",
    },
    {
        "cell_line_name": "UACC-257",
        "depmap_id": "ACH-000676",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },
    {
        "cell_line_name": "UACC62",
        "depmap_id": "ACH-000680",
        "tissue": "Skin / Melanoma",
        "cancer_type": "Malignant Melanoma",
        "lineage": "skin",
        "keywords": "melanoma,skin,skin cancer,cutaneous melanoma",
    },

    # Kidney / Renal (8 lines)
    {
        "cell_line_name": "A498",
        "depmap_id": "ACH-000300",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,clear cell renal,kidney cancer,renal cancer,nephroma",
    },
    {
        "cell_line_name": "786-0",
        "depmap_id": "ACH-000494",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma (Clear cell / VHL-null)",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,clear cell renal,kidney cancer,renal cancer,vhl",
    },
    {
        "cell_line_name": "ACHN",
        "depmap_id": "ACH-000159",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,kidney cancer,renal cancer",
    },
    {
        "cell_line_name": "CAKI-1",
        "depmap_id": "ACH-000570",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma (Clear cell)",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,clear cell renal,kidney cancer,renal cancer",
    },
    {
        "cell_line_name": "RXF 393",
        "depmap_id": "ACH-000844",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,kidney cancer,renal cancer",
    },
    {
        "cell_line_name": "SN12C",
        "depmap_id": "ACH-000164",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,kidney cancer,renal cancer",
    },
    {
        "cell_line_name": "TK-10",
        "depmap_id": "ACH-000465",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,kidney cancer,renal cancer",
    },
    {
        "cell_line_name": "UO-31",
        "depmap_id": "ACH-000889",
        "tissue": "Kidney / Renal",
        "cancer_type": "Renal Cell Carcinoma",
        "lineage": "kidney",
        "keywords": "renal,kidney,renal cell carcinoma,rcc,kidney cancer,renal cancer",
    },

    # Prostate (3 lines)
    {
        "cell_line_name": "PC-3",
        "depmap_id": "ACH-000778",
        "tissue": "Prostate",
        "cancer_type": "Prostate Carcinoma (Castration-resistant)",
        "lineage": "prostate",
        "keywords": "prostate,prostate cancer,prostate carcinoma,crpc,adenocarcinoma of prostate",
    },
    {
        "cell_line_name": "DU-145",
        "depmap_id": "ACH-000783",
        "tissue": "Prostate",
        "cancer_type": "Prostate Carcinoma (Androgen-insensitive)",
        "lineage": "prostate",
        "keywords": "prostate,prostate cancer,prostate carcinoma,crpc",
    },
    {
        "cell_line_name": "VCAP",
        "depmap_id": "ACH-000961",
        "tissue": "Prostate",
        "cancer_type": "Prostate Carcinoma (Androgen receptor+)",
        "lineage": "prostate",
        "keywords": "prostate,prostate cancer,prostate carcinoma,ar+",
    },

    # Blood / Hematologic (8 lines)
    {
        "cell_line_name": "K-562",
        "depmap_id": "ACH-000551",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Chronic Myelogenous Leukemia (CML / BCR-ABL+)",
        "lineage": "myeloid",
        "keywords": "leukemia,cml,chronic myeloid leukemia,myelogenous,blood,hematologic,bcr-abl,blast crisis",
    },
    {
        "cell_line_name": "CCRF-CEM",
        "depmap_id": "ACH-000085",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Acute Lymphoblastic Leukemia (T-ALL)",
        "lineage": "lymphoid",
        "keywords": "leukemia,all,acute lymphoblastic leukemia,t-cell leukemia,blood,hematologic",
    },
    {
        "cell_line_name": "MOLT-4",
        "depmap_id": "ACH-000362",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Acute Lymphoblastic Leukemia (T-ALL)",
        "lineage": "lymphoid",
        "keywords": "leukemia,all,acute lymphoblastic leukemia,t-cell leukemia,blood,hematologic",
    },
    {
        "cell_line_name": "RPMI-8226",
        "depmap_id": "ACH-000174",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Multiple Myeloma (Plasmacytoma)",
        "lineage": "lymphoid",
        "keywords": "myeloma,multiple myeloma,plasma cell,plasmacytoma,blood,hematologic",
    },
    {
        "cell_line_name": "HDLM-2",
        "depmap_id": "ACH-000188",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Hodgkin Lymphoma",
        "lineage": "lymphoid",
        "keywords": "lymphoma,hodgkin,hodgkins lymphoma,blood,hematologic",
    },
    {
        "cell_line_name": "L-1236",
        "depmap_id": "ACH-000122",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Hodgkin Lymphoma",
        "lineage": "lymphoid",
        "keywords": "lymphoma,hodgkin,hodgkins lymphoma,blood,hematologic",
    },
    {
        "cell_line_name": "L-428",
        "depmap_id": "ACH-000078",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Hodgkin Lymphoma",
        "lineage": "lymphoid",
        "keywords": "lymphoma,hodgkin,hodgkins lymphoma,blood,hematologic",
    },
    {
        "cell_line_name": "SR",
        "depmap_id": "ACH-000874",
        "tissue": "Blood / Hematologic",
        "cancer_type": "Large Cell Immunoblastic Lymphoma",
        "lineage": "lymphoid",
        "keywords": "lymphoma,large cell lymphoma,blood,hematologic",
    },

    # Bone / Sarcoma / Soft Tissue (2 lines)
    {
        "cell_line_name": "TC-71",
        "depmap_id": "ACH-000109",
        "tissue": "Bone / Sarcoma",
        "cancer_type": "Ewing Sarcoma",
        "lineage": "bone",
        "keywords": "sarcoma,ewing,ewings sarcoma,ewing sarcoma,bone cancer,osteosarcoma,bone",
    },
    {
        "cell_line_name": "RD",
        "depmap_id": "ACH-000288",
        "tissue": "Soft Tissue / Sarcoma",
        "cancer_type": "Rhabdomyosarcoma",
        "lineage": "soft_tissue",
        "keywords": "sarcoma,rhabdomyosarcoma,soft tissue sarcoma,muscle,childhood cancer",
    },
]

# Validation
meta_names = {row["cell_line_name"] for row in metadata}
missing = set(expected_cell_lines) - meta_names
extra = meta_names - set(expected_cell_lines)
assert not missing, f"Missing cell lines: {missing}"
assert not extra, f"Extra cell lines: {extra}"
assert len(metadata) == len(expected_cell_lines) == 80, f"Expected 80, got {len(metadata)}"

out_path = "data/processed/cell_line_metadata.csv"
with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["cell_line_name", "tissue", "cancer_type", "lineage", "depmap_id", "keywords"])
    writer.writeheader()
    for row in sorted(metadata, key=lambda x: x["cell_line_name"].lower()):
        writer.writerow(row)

print(f"Successfully created {out_path} with {len(metadata)} cell lines.")
